chore: update devcontainer build for improved setup and dependencies

diff --git a/.devcontainer/Containerfile b/.devcontainer/Containerfile
--- a/.devcontainer/Containerfile
+++ b/.devcontainer/Containerfile
@@ -1,8 +1,12 @@
+# Use the official Microsoft Dev Container image with Miniconda
 FROM mcr.microsoft.com/devcontainers/miniconda:1-3
-# FROM docker.io/continuumio/miniconda3
 
+# Install additional dependencies and clean up
+# TODO: Use conda-linux-64.dev.lock instead of environment.yaml
 COPY environment.yaml /tmp/conda-tmp/
-RUN if [ -f "/tmp/conda-tmp/environment.yaml" ]; then umask 0002 && /opt/conda/bin/conda env update -n base -f /tmp/conda-tmp/environment.yaml; fi \
+RUN set -eux \
+    && umask 0002 \
+    && /opt/conda/bin/conda env update -n base -f /tmp/conda-tmp/environment.yaml \
+    && /opt/conda/bin/conda install -c conda-forge -y pytest-cov conda-lock pylint pytest \
+    && /opt/conda/bin/conda clean -afy \
     && rm -rf /tmp/conda-tmp
-
-RUN conda install -c conda-forge -y pylint pytest
